### ISSUE TITLE
cell numbers of the Alzheimer dataset

### ISSUE THREAD

**Issue by yeqing97** [Teddy-XiongGZ/DeepGSEA#3]
Hi,

Thank you for your excellent work on DeepGSEA.

I have a question regarding the Alzheimer dataset. I downloaded the data from this link (https://singlecell.broadinstitute. org/single_cell/study/SCP1375), but I noticed that the shape of the expression_matrix_normalized is (2766, 72165). This suggests the dataset contains 72,165 cells, whereas Table 1 indicates there are 16,692 cells.

I am concerned that I may have missed something or made an error in my operation. Could you please clarify this discrepancy?

Thank you.

**Comment by gzxiong** [comment]
Since we are comparing the disease group with the control group, only instances with "8months-disease-replicate_1" or "8months-control-replicate_1" labels are selected for an apple-to-apple comparison. That's why only 16,692 cells are used in the experiments. More details can be found at https://github.com/Teddy-XiongGZ/DeepGSEA/blob/main/deepgsea/load_data.py#L317.
